name: Filter out the coin

on:
  issue_comment:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Post Issue comment
      uses: SusannedVBM/testCC2RegexRepository@master
      if: github.event.comment.body == 'I want to solve this issue'
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        message: 'Thank you very much. Please fork this repository and raise the PR when ready '
